<?php


//================================== TASK 3===================================//
/**
 * Implements hook_menu().
 */
function training_menu() {
  $items ['training/files'] = [
    'title' => "Uploaded files",
    'page callback' => 'training_files_page',
    'description' => 'Uploaded files page',
    'file' => 'training.pages.inc',
    'access callback' => 'user_is_logged_in',
  ];

  $items['training/files/%ctools_js'] = array(
    'page callback' => 'training_modal_call',
    'page arguments' => array(2),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function training_modal_call($ajax) {
  if ($ajax) {
    ctools_include('ajax');
    ctools_include('modal');

    $form_state = array(
      'ajax' => TRUE,
      'title' => t('File uploading form'),
    );

    $output = ctools_modal_form_wrapper('file_upload_form', $form_state);

    if (!empty($form_state['ajax_commands'])) {
      $output = $form_state['ajax_commands'];
    }

    // Return the ajax instructions to the browser via ajax_render().
    print ajax_render($output);
    drupal_exit();
  }
  else {
    return drupal_get_form('file_upload_form');
  }
}

function file_upload_form($form, $form_state) {
  $form = array();

  $form['user_file'] = array(
    '#title' => t('Choose file to upload'),
    '#name' => 'user_file',
    '#type' => 'managed_file',
    '#upload_location' => 'private://user_files/',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Choose file to upload'),
  );
  return $form;
}



function file_upload_form_submit(&$form, &$form_state) {
  ctools_include('modal');
  ctools_modal_add_js();

  if ($form['user_file']['#file']){
    $form['user_file']['#file']->status = FILE_STATUS_PERMANENT;
    file_save($form['user_file']['#file']);

  }

  $form_state['ajax_commands'] []= ctools_modal_command_dismiss();
  training_load_managed_files();
  training_dropSettings('loaded', FALSE);
  //drupal_exit();
}

function add_set($str){
   ctools_include('ajax');
   drupal_add_js(array('myModule' => array('key' => 'value')), 'setting');
 }

function training_load_managed_files() {
  $files = db_select('file_managed', 'fm')
    ->fields('fm', array('fid', 'uid', 'uri', 'status'))
    ->condition('uri', '%user_files%', 'LIKE')
    ->execute()
    ->fetchAll();

  if (!empty($files)){
    foreach ($files as &$file){
      $file->uri = file_create_url($file->uri);
    }
  }

  drupal_add_js(array('files' => $files, ), 'setting');
}

/**
 * Implements hook_file_download().
 */
function training_file_download($uri) {
  if (training_user_has_files()){
    $file = array_values( file_load_multiple(array(), array('uri' => $uri)))[0];
    return array(
      'Content-Type' => $file->filemime,
    );
  }

  return -1;
}

function training_user_has_files() {
  global $user;
  $files = db_select('file_managed', 'fm')
    ->fields('fm', array('uid'))
    ->condition('uri', '%user_files%', 'LIKE')
    ->condition('uid', $user->uid)
    ->range(0,1)
    ->execute()
    ->fetchAll();
  if (!empty($files)) return TRUE;

  return FALSE;
}

function training_dropSettings($name, $setting){
  drupal_add_js(array($name => $setting), 'setting');
}